steps:
# Install node dependencies
- name: 'node:10.10.0'
  entrypoint: 'npm'
  args: ['install']
# Build the helloworld container image.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/${PROJECT_ID}/kubdev-node-server-a:${COMMIT_SHA}'
  - '.'
# Retrieve and decrypt the GitHub Hub configuration.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gsutil cp gs://${PROJECT_ID}-build-configs/hub.enc hub.enc

    gcloud kms decrypt \
        --ciphertext-file hub.enc \
        --plaintext-file /config/hub \
        --location global \
        --keyring ${_KMS_KEYRING} \
        --key ${_KMS_KEY}
  volumes:
  - name: 'config'
    path: /config
# Generate a kubeconfig file for the given GKE cluster.
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  - 'KUBECONFIG=/kube/config'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    CLUSTER=$$(gcloud config get-value container/cluster)
    PROJECT=$$(gcloud config get-value core/project)
    ZONE=$$(gcloud config get-value compute/zone)

    gcloud container clusters get-credentials "$${CLUSTER}" \
      --project "$${PROJECT}" \
      --zone "$${ZONE}"
  volumes:
  - name: 'kube'
    path: /kube
- name: 'gcr.io/cloud-builders/go'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    go get github.com/github/hub && cd $${GOPATH}/src/github.com/github/hub
    make install

    ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")

    hub config --global credential.https://github.com.helper /usr/local/bin/hub-credential-helper
    hub config --global hub.protocol https
    hub config --global user.email "$${ACTIVE_ACCOUNT}"
    hub config --global user.name "Google Container Builder"
    hub clone "https://github.com/${_GITHUB_USERNAME}/kubdev-infra-dev.git"

    cd kubdev-infra-dev

    cat <<EOF < path.yml
    spec:
      template:
        spec:
          containers:
          - name: kubdev-node-server-a
            image: gcr.io/${PROJECT_ID}/kubdev-node-server-a:${COMMIT_SHA}
    EOF

    kubectl patch --local -o -yaml \
      -f kubernetes/deployements/kubdev-node-server-a.yaml
      -p "$(cat path.yaml)" \
      > kubdev-node-server-a.yaml

    hub commit -F- <<EOF
    Update the node-server-a application

    This commit updates the kubdev-node-server-a deployement container image to:
      gcr.io/${PROJECT_ID}/kubdev-node-server-a:${COMMIT_SHA}
    Build ID: ${BUILD_ID}
    EOF

    hub push origin master
  volumes:
  - name: 'config'
    path: /config
  - name: 'kube'
    path: /kube

images: ['gcr.io/${PROJECT_ID}/kubdev-node-server-a:${COMMIT_SHA}']
